### ISSUE TITLE
Getting "This module can only be run on a Raspberry Pi!" in Banana Pi M5 running Armbian 23 with kernel 6.1.30-meson64

### ISSUE THREAD

**Issue by aalku** [Dangku/RPi.GPIO-Amlogic#4]
Hi! It seems the detection of the board is not working in my board running Armbian 23 with kernel 6.1.30-meson64

I get this error:
```
pi@bananapim5:~$ sudo python3 auto-fan.py 
Traceback (most recent call last):
  File "/home/pi/auto-fan.py", line 2, in <module>
    import RPi.GPIO as GPIO
  File "/usr/local/lib/python3.10/dist-packages/RPi.GPIO-0.7.1-py3.10-linux-aarch64.egg/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
```

Looking at the code I think the problem is that I get no "Hardware" section in /proc/cpuinfo:

```
cat /proc/cpuinfo
processor       : 0
model name      : ARMv8 Processor rev 0 (v8l)
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd05
CPU revision    : 0

processor       : 1
model name      : ARMv8 Processor rev 0 (v8l)
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd05
CPU revision    : 0

processor       : 2
model name      : ARMv8 Processor rev 0 (v8l)
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd05
CPU revision    : 0

processor       : 3
model name      : ARMv8 Processor rev 0 (v8l)
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd05
CPU revision    : 0
```

I think we could use this, but I don't think if you know a better way:
```
grep BOARD_NAME /etc/armbian-image-release
BOARD_NAME="Banana Pi M5"
```

I might code it myself but I wish to get at least your advice.

**Comment by aalku** [comment]
I added this so I think the board gets detected but there's a new error. I guess the module is not compatible with the kernel or something, right?

![image](https://github.com/Dangku/RPi.GPIO-Amlogic/assets/12587056/df7009dc-5411-49bf-9a21-b58191f07a77)


I get this:
```
Traceback (most recent call last):
  File "/home/pi/auto-fan.py", line 2, in <module>
    import RPi.GPIO as GPIO
  File "/usr/local/lib/python3.10/dist-packages/RPi.GPIO-0.7.1-py3.10-linux-aarch64.egg/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
SystemError: initialization of _GPIO raised unreported exception
```

I'll try to find out where does that unreported error come from.

**Comment by aalku** [comment]
Ok. I needed to initialize "revision" variable. It needs to have a length, a \0, I guess, It makes sense.

![image](https://github.com/Dangku/RPi.GPIO-Amlogic/assets/12587056/013287b9-c788-4414-9923-89e677ba6ae6)

I don't know why prints here or there totally changed the probability of crash but once I fixed that variable then it works as expected.

So the pending thing is if we detect the board this way or how.

**Comment by Dangku** [comment]
it's only for bananapi amlogic 4.9 kernel ubuntu/debian image, no support third part images like armbian.

**Comment by aalku** [comment]
Ok. Thanks. I'll leave my fork online then. It works for me and maybe it will help someone else.

https://github.com/aalku/RPi.GPIO-Amlogic-BPiM5

Thanks again. Great job.
